<a href="https://colab.research.google.com/github/LeonardoMafra/Python_Data_Science/blob/main/Numpy_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#Libraries

import numpy as np

In [4]:
#pesos

w1,w2,w3 = 0.3, 0.2, 0.5

print(w1,w2,w3)



0.3 0.2 0.5


In [2]:
#dados climaticos da regiao A

regiaoA_temp = 22
regiaoA_chuva = 67
regiaoA_umidade = 65

In [6]:
#aplicação do modelo

regiaoA_goiaba = (regiaoA_temp * w1) + (regiaoA_chuva * w2) +  (regiaoA_umidade * w3)

print(f'Na regiao A a producao de goiaba foi de {regiaoA_goiaba} toneladas por hectare.')

Na regiao A a producao de goiaba foi de 52.5 toneladas por hectare.


In [16]:
#Lista com os valores de temperatura, chuva e umidade
regiaoA =[22,67,65]
regiaoB =[24,88,95]
regiaoC =[17,134,50]
regiaoD=[18,96,70]



In [15]:
#lista com os valores dos pesos para os calculos
pesos = [w1,w2,w3]

In [38]:
#Funcao para realizar o calculo da produção de goiaba por hectare
def producao_goiaba(regiao, pesos):
  result = 0
  for x, w in zip(regiao,pesos):
    result += x * w
  return result

In [44]:
#Producao por hectare na regiao A

print(f'A producao pro hectare na regiao A foi de: {producao_goiaba(regiaoA,pesos)} toneladas')

#Producao por hectare na regiao B

print(f'A producao pro hectare na regiao B foi de: {producao_goiaba(regiaoB,pesos)} toneladas')

#Producao por hectare na regiao C

print(f'A producao pro hectare na regiao C foi de: {producao_goiaba(regiaoC,pesos)} toneladas')

#Producao por hectare na regiao D

print(f'A producao pro hectare na regiao D foi de: {producao_goiaba(regiaoD,pesos)} toneladas')

A producao pro hectare na regiao A foi de: 52.5 toneladas
A producao pro hectare na regiao B foi de: 72.3 toneladas
A producao pro hectare na regiao C foi de: 56.9 toneladas
A producao pro hectare na regiao D foi de: 59.6 toneladas


In [ ]:
#USANDO O NUMPY


In [48]:
#definindo as regioes e os pesos com np.array([])

regiaoA = np.array([22,67,65])
regiaoB = np.array([24,88,95])
regiaoC = np.array([17,134,50])
regiaoD = np.array([18,96,70])
pesos = np.array([w1,w2,w3])


print(type(regiaoA))
print(type(pesos))



<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [50]:
# realizando calculo usando as função np.dot

reg_a = np.dot(regiaoA,pesos)
reg_b = np.dot(regiaoB,pesos)
reg_c = np.dot(regiaoC,pesos)
reg_d = np.dot(regiaoD,pesos)

print(f'A producao pro hectare na regiao A foi de: {reg_a} toneladas')
print(f'A producao pro hectare na regiao B foi de: {reg_b} toneladas')
print(f'A producao pro hectare na regiao C foi de: {reg_c} toneladas')
print(f'A producao pro hectare na regiao D foi de: {reg_d} toneladas')

A producao pro hectare na regiao A foi de: 52.5 toneladas
A producao pro hectare na regiao B foi de: 72.3 toneladas
A producao pro hectare na regiao C foi de: 56.9 toneladas
A producao pro hectare na regiao D foi de: 59.6 toneladas


In [55]:
# Exemplos em Numpy

#lista em python

arr1 = list(range(2000000))
arr2 = list(range(1000000,3000000))

#vetor em Numpy

arr1_np = np.array(arr1)
arr2_np = np.array(arr2)



In [56]:
#teste de tempo realizando o calculo normal

%%time

result = 0
for x1,x2 in zip(arr1,arr2):
  result += x1 * x2
print(result)

4666663666667000000
CPU times: user 773 ms, sys: 0 ns, total: 773 ms
Wall time: 797 ms


In [57]:
%%time
print(np.dot(arr1_np, arr2_np))

4666663666667000000
CPU times: user 5.83 ms, sys: 0 ns, total: 5.83 ms
Wall time: 4.85 ms


In [66]:
# matriz com dos dados climaticos

dados_climaticos = np.array([[22,67,65],
                            [24,88,95],
                            [17,134,50],
                            [18,96,70]])

print(dados_climaticos)

print(dados_climaticos.shape) # retorna o tamanho do array
print(pesos.shape) # retorna o tamanho do array

print(pesos.dtype) # retorna o tipo do valor
print('---------------------------')
print(dados_climaticos.dtype) # retorna o tipo do valor

[[ 22  67  65]
 [ 24  88  95]
 [ 17 134  50]
 [ 18  96  70]]
(4, 3)
(3,)
float64
---------------------------
int64


In [67]:
#finalizando calculo da produção de goiaba em um unico calculo
np.matmul(dados_climaticos,pesos)

array([52.5, 72.3, 56.9, 59.6])

In [68]:
#finalizando calculo da produção de goiaba em um unico calculo
dados_climaticos @ pesos

array([52.5, 72.3, 56.9, 59.6])